
from enum import Enum, IntEnum, StrEnum, auto
from typing import Any, Dict, Final

from telegram import (
    ReplyKeyboardMarkup,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
)

GO_BACK: Final = "Назад"
GO_BACK_CALLBACK_DATA: Final = -1

# TODO: In questions use separate dates for when a question was asked and when
# a question was answered

# For every question there is a notification
# Admins can answer questions in a spree
# In a spree admins are given questions one by one until there are no left
# Spree mode can be left at any moment

# Admins log in using passwords generated by the superadmin
# Passwords are linked to admins (as users in telegram) on first login
# Upon first login the admin specifies their name

# TODO: Add template answer "Look at FAQ" (make editable through admin panel)
# TODO : Add a list of users who are expecting an answer
# TODO: Change question viewing to question deletion.

# Admin menu options:
# - question spree
# - settings
# - superadmin (for superadmins)

# When answering a question admins can choose:
# - a template answer (add confirmation)
# - redirect the question to a different department
#   (make sure notifications still work)
# - discard (with template "Sorry, we can't answer that")
# - skip (in next 5/4)
# - stop answering questions

# Settings:
# - Set admin name (max 100 symbols)
# - Log out

# Superadmin settings:
# - Bot shutdown (with a template "sorry" message)
# - Global message for all
# - Global message for those awaiting an answer
# - Download db as file
# - Edit message templates
# - Add admin
# - See admin names
# - Delete and log out admins

# TODO: Look at hostings' data/resource allowance!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# TODO: Consider sqlite for data storage
# Availablle hostings:
# - fps.ms
# - PythonAnywhere
# - HelioHost
# - Replit
# - Glitch
# - Heroku
# - GitHub pages
# - Google Colab (Jupyter Notebook integration?)


class SharedDynamicDataClass:

    def __init__(self, new_data: Dict[Any, Any]):
        self.data = new_data


dynamic_data = SharedDynamicDataClass({})


# TODO: Make changeable through the bot interface
class Strings (StrEnum):
    INTRO = "Первое сообщение которое видит пользователь в чате"
    MAIN_MENU: str | None = "По возвращении в главное меню"
    FAQ = "- <a href='https://pedklassy.bspu.by/wp-content/uploads/2025/02/zvo\
prosy-k-sobesedovaniju-.zdzocx'>Примерные вопросы к собеседованию</a>\n- <a hr\
ef='https://pedklassy.bspu.by/abiturientu-pedklassovcu/algoritm-lgotnogo-postu\
plenija-dlja-pedklassovcev/'>Алгоритм льготного поступления для педклассовцев]\
</a>"
    EVENTS = "О том как нас пригласиxть и какие у нас мероприятия"
    SOCIALS = "Наши соцсети!"
    QUESTION_MENU = "Про вопросики и что вы с ними можете делать"
    VIEW_QUESTIONS = "Ваши вопросики в кнопочках снизу (чтобы сразу выбрать)"
    EXPERTS = "Вот сюда-то вы можете обращаться"
    ASK_QUESTION = "Вот теперь задавайте ваш вопрос."
    QUESTION_TOO_SHORT = "Такие коротенькие вопросы мы считаем ошибочками."
    THANKS_FOR_QUESTION = "\
Благодарим за ваш вопрос. Вскоре его рассмотрят наши специалисты"
    MAIN_MENU_FALLBACK = "Моя твоя не понимать"
    QUESTIONS_MENU_FALLBACK = QUESTION_MENU


class Experts(StrEnum):
    ONE = "Отдел по вопросам вопросов"
    TWO = "Отдел по вопросам невопросов"
    THREE = "Отдел по вопросам исключённого третьего"


class MainKeyboardOptions(StrEnum):
    FAQ = "Часто задаваемые вопросы!"
    EVENTS = "Как нас пригласить? Мероприятия."
    SOCIALS = "Наши сети!"
    QUESTION = "Задайте нам вопрос!"


class QuestionsKeyboardOptions(StrEnum):
    ASK_QUESTION = "Задать вопрос"
    SEE_QUESTIONS = "Увидеть свои вопросы"


class Action (Enum):
    MAIN_MENU = auto()
    QUESTION_MENU = auto()
    RETURN_TO_QUESTION_MENU = auto()
    EXPERT_MENU = auto()
    CHOOSE_QUESTION = auto()
    QUESTION = auto()


MAIN_KEYBOARD = ReplyKeyboardMarkup(
    keyboard=[[item] for item in MainKeyboardOptions],
    one_time_keyboard=True,
    is_persistent=True)


QuestionsList = list(QuestionsKeyboardOptions)

QUESTIONS_KEYBOARD = InlineKeyboardMarkup(
    inline_keyboard=[[InlineKeyboardButton(
        str(item),
        callback_data=list(QuestionsKeyboardOptions).index(item))]
                    for item in QuestionsKeyboardOptions] +
    [[InlineKeyboardButton(text=str(GO_BACK),
                           callback_data=GO_BACK_CALLBACK_DATA)]])


ExpertsList = list(Experts)

EXPERT_KEYBOARD: Final = InlineKeyboardMarkup(
    inline_keyboard=[[InlineKeyboardButton(
        str(item),
        callback_data=ExpertsList.index(item))]
                     for item in Experts] +
    [[InlineKeyboardButton(text=str(GO_BACK),
                           callback_data=GO_BACK_CALLBACK_DATA)]],
)


class PasswordFormat(IntEnum):
    PARTS = 3
    PART_LENGTH = 6


class Keywords(IntEnum):
    SELECTED_EXPERT = auto()


class DatabaseTables(StrEnum):
    QUESTIONS = 'questions'
    ADMINS = 'admins'


class FileNames(StrEnum):
    PERSISTENCE = "persistence.bin"
    DEFAULTS = "defaults.json"
    DB = "data.db"
    DB_SETUP = "db_setup.log"
