from enum import Enum, IntEnum, StrEnum, auto

# TODO: In questions use separate dates for when a question was asked and when
# a question was answered

# For every question there is a notification
# Admins can answer questions in a spree
# In a spree admins are given questions one by one until there are no left
# Spree mode can be left at any moment

# Admins log in using passwords generated by the superadmin
# Passwords are linked to admins (as users in telegram) on first login
# Upon first login the admin specifies their name

# TODO: Add template answer "Look at FAQ" (make editable through admin panel)
# TODO : Add a list of users who are expecting an answer
# TODO: Change question viewing to question deletion.

# Admin menu options:
# - question spree
# - settings
# - superadmin (for superadmins)

# When answering a question admins can choose:
# - a template answer (add confirmation)
# - redirect the question to a different department
#   (make sure notifications still work)
# - discard (with template "Sorry, we can't answer that")
# - skip (in next 5/4)
# - stop answering questions

# Settings:
# - Set admin name (max 100 symbols)
# - Log out

# Superadmin settings:
# - Bot shutdown (with a template "sorry" message)
# - Global message for all
# - Global message for those awaiting an answer
# - Download db as file
# - Edit message templates
# - Add admin
# - See admin names
# - Delete and log out admins

# TODO: Look at hostings' data/resource allowance!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# TODO: Consider sqlite for data storage
# Availablle hostings:
# - fps.ms
# - PythonAnywhere
# - HelioHost
# - Replit
# - Glitch
# - Heroku
# - GitHub pages
# - Google Colab (Jupyter Notebook integration?)

GO_BACK_CODE = -1


# TODO: Add QuestionState
class State(Enum):
    MAIN_MENU = auto()
    QUESTION_MENU = auto()
    DEPARTMENT_MENU = auto()
    QUESTION_VIEW_MENU = auto()
    ASKING_QUESTION = auto()
    VIEWING_QUESTION = auto()


class AdminState(Enum):
    LOGIN = auto()
    MAIN_MENU = auto()
    SETTINGS = auto()
    CHANGING_TEXT = auto()
    ENTERING_NAME = auto()


class Keyboards(Enum):
    MAIN_MENU = auto()
    QUESTION_MENU = auto()
    DEPARTMENTS = auto()
    VIEW_MESSAGE = auto()
    ADMIN_MENU = auto()
    ADMIN_SETTINGS = auto()
    SU_ADMIN_SETTINGS = auto()
    ADMIN_ANSWER_MENU = auto()


class BotMemory(IntEnum):
    SELECTED_DEPARTMENT = auto()
    VIEWED_MSG = auto()
    LOGGED_IN_AS = auto()


class PasswordFormat(IntEnum):
    PARTS = 3
    PART_LENGTH = 6


class DatabaseTables(StrEnum):
    QUESTIONS = "questions"
    ADMINS = "admins"


class FileNames(StrEnum):
    CONFIG = "config.ini"
    PERSISTENCE = "persistence.bin"
    DEFAULTS = "defaults.json"
    DB = "data.db"
    DB_SETUP = "db_setup.log"
