from enum import Enum, IntEnum, StrEnum, IntFlag, auto

# For every question there is a notification
# Admins can answer questions in a spree
# In a spree admins are given questions one by one until there are no left
# Spree mode can be left at any moment

# Admins log in using passwords generated by the superadmin
# Passwords are linked to admins (as users in telegram) on first login
# Upon first login the admin specifies their name

# TODO: Add template answer "Look at FAQ" (make editable through admin panel)
# TODO : Add a list of users who are expecting an answer

# Admin menu options:
# - question spree
# - settings
# - superadmin (for superadmins)

# When answering a question admins can choose:
# - a template answer (add confirmation)
# - redirect the question to a different department
#   (make sure notifications still work)
# - discard (with template "Sorry, we can't answer that")
# - skip (in next 5/4)
# - stop answering questions

# Settings:
# - Set admin name (max 100 symbols)
# - Log out

# Superadmin settings:
# - Bot shutdown (with a template "sorry" message)
# - Global message for all
# - Global message for those awaiting an answer
# - Download db as file
# - Edit message templates
# - Add admin
# - See admin names
# - Delete and log out admins

# TODO: Look at hostings' data/resource allowance!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Availablle hostings:
# - fps.ms
# - PythonAnywhere
# - HelioHost
# - Replit
# - Glitch
# - Heroku
# - GitHub pages
# - Google Colab (Jupyter Notebook integration?)

# - Динамическая система отделов
# - Ответы на вопросы пора прикрутить
# - Изменения текста в боте

# - Make database interactions CRUD
#   - Create python objets with CRUD functions that link to database
# - Split handler functions by logic
# - Take a look at functools partial to simplify decorators
# - Study SOLID principles and apply, orthogonality
# - Optimise use of functions
# - Take inspiration from Web Design
# - Pragmatic Programmer?
# - Learn Swift UI as practice of similar patterns
GO_BACK_CODE = -1


class MainMenuState(Enum):
    MAIN_MENU = auto()
    ERROR_ENCOUNTERED = auto()


class QuestionState(Enum):
    MAIN_MENU = auto()
    DEPARTMENT_MENU = auto()
    QUESTION_VIEW_MENU = auto()
    ASKING_QUESTION = auto()
    VIEWING_QUESTION = auto()


class AdminState(Enum):
    LOGIN = auto()
    MAIN_MENU = auto()
    ANSWERING_QUESTIONS = auto()
    SETTINGS = auto()
    SU_SETTINGS = auto()
    MAINTAINER_SETTINGS = auto()
    CHANGING_TEXT = auto()
    ENTERING_NAME = auto()
    ENTERING_DEPARTMENT_NAME = auto()
    SELECTING_DEPARTMENT = auto()
    SELECTING_DEPARTMENT_TO_DELETE = auto()
    SELECTING_DEPARTMENT_TO_REDIRECT = auto()
    SELECTING_ADMIN_TO_DELETE = auto()
    CONFIRMING_QUESTION_DELETION = auto()


class AdminFlags(IntFlag):
    IS_SUPER = 1
    IS_MAINTAINER = 2
    NAME_UPDATES = 4
    LOG_ERRORS = 8


class Keyboards(Enum):
    MAIN_MENU = auto()
    QUESTION_MENU = auto()
    DEPARTMENTS = auto()
    VIEW_MESSAGE = auto()
    ADMIN_SETTINGS = auto()
    SU_ADMIN_SETTINGS = auto()
    MAINTAINER_SETTINGS = auto()
    ADMIN_ANSWER_MENU = auto()
    GO_BACK = auto()
    CONFIRM = auto()


class BotMemory(IntEnum):
    SELECTED_DEPARTMENT = auto()
    ADMIN_SELECTED_DEPARTMENT = auto()
    VIEWED_MSG = auto()
    LOGGED_IN_AS = auto()
    STARTED_CHAT = auto()
    ADMIN_REVIEWS_QUESTION = auto()
    QUESTIONS_UNDER_REVIEW = auto()
    QUESTIONS_TO_SKIP = auto()


class PasswordFormat(IntEnum):
    PARTS = 3
    PART_LENGTH = 6


class DatabaseTables(StrEnum):
    QUESTIONS = "questions"
    ADMINS = "admins"


class FileNames(StrEnum):
    CONFIG = "config.ini"
    PERSISTENCE = "persistence.bin"
    DEFAULTS = "defaults.json"
    DB = "data.db"
    FIRST_SU_PASSWORD = "su.log"
    LOG = "rotating.log"
